### PR TITLE
fix(field): Show field in rest api

### LINKED ISSUE #61: Field is missing from REST API
Hey Brandon, first of all, huge thanks for all your fantastic work!

Recently I discovered that the field is missing from the REST API.

I fixed it by using `acf_register_field_type` instead of the two filters. 
Maybe I am missing something but everything seems to work fine.

All the best,
Daniel

### PR DESCRIPTION
**Pull request by Dathix**
Fix #61

### CODE REVIEW

File: plugin.php [hunk 1]
```diff
@@ -45,14 +45,22 @@ public function __invoke()
...
+            plugin_dir_path(__FILE__) . $this->assetPath
+        );
+
+        acf_register_field_type($field);
+
+        // Prevent problems with acf_format=standard
+        add_filter(
+            "acf/rest/format_value_for_rest/type={$field->name}",
+            function ($value_formatted, $post_id, $field, $value) {
+                return $value;
```
Comment (Dathix) [inline plugin.php:59]: We should go with `return (new PhoneNumber($value))->toArray();` to provide all the fields. @Log1x What do you think?

Comment (Log1x) [reply plugin.php:59]: definitely

Comment (Log1x) [reply plugin.php:59]: do we need to do any conditionals to check if $value is empty? we could also do a `->isValid()` check on the PhoneNumber instance before converting to array

Comment (Log1x) [reply plugin.php:59]: although I guess field validation would already handle that now that I think about it

Comment (Dathix) [reply plugin.php:59]: Yeah, you're right but let's do both to be sure.

Comment (Dathix) [reply plugin.php]: Okay, I think we can revert the changes because "dry". `PhoneNumber` does everything already: https://github.com/Log1x/acf-phone-number/blob/master/src/PhoneNumber.php#L256-L258

Comment (Log1x) [reply plugin.php]: oh oops 😊 that's fair. as does the construct

Comment (Log1x) [reply plugin.php]: can just return it outright with `return (new PhoneNumber($value))->toArray()` I think

**Comment by Log1x** [comment]
Did some quick digging and found https://github.com/AdvancedCustomFields/acf/blob/acf66384bd2100150e30d71443812bc52bbe0c5c/includes/fields/class-acf-field.php#L346-L348

We can add this logic directly to [`PhoneNumberField`](https://github.com/Log1x/acf-phone-number/blob/master/src/PhoneNumberField.php) and avoid using a filter.

**Comment by Dathix** [comment]
Sounds great in theory but does only seem to work with the default `acf_format` `light`, but not with `standard`.

**Comment by Log1x** [comment]
> Sounds great in theory but does only seem to work with the default `acf_format` `light`, but not with `standard`.

That's super annoying.

**Comment by Log1x** [comment]
That's so strange. I see it being used all over the place in core ACF fields (e.g. https://github.com/AdvancedCustomFields/acf/blob/0d9af119fd6bce7691bfb7582fe1f465441d2955/includes/fields/class-acf-field-true_false.php#L316)

Potential bug?

**Comment by Log1x** [comment]
https://github.com/AdvancedCustomFields/acf/blob/c2d6fd0a07def8288c7ee6beeb0a5f94110b3e34/includes/rest-api/acf-rest-api-functions.php#L70-L72

😕

**Comment by Dathix** [comment]
Really annoying, so the filter seems to be the best option...
